ying = {} # Default pallete, nothing is changed!

[yinglemon]
	main = "#ff0"
	line = "#6a6a1c"
	dark = "#cc0"
	lid  = "#808000"
	hand = "#aa0"
	tongue="#d40000"

[yinglime]
	main = "#9f8"
	eye = "#cff"
	line = "#131"
	dark = "#3b4"
	lid =  "#474"
	hand = "#474"
	tongue = "#141"
	hair = "#262"
	tail = "#262"
	show_all = true

[myno]
	main="#e4d9b9"
	eye = "#cdebfd"
	line = "#880056"
	dark = "#a99f8b"
	lid = "#a99f8b"
	hand = "#a99f8b"
	hair = "#913fef"
	tail = "#913fef"
	tongue = "#ff66aa"
	show_all = true

[thio]
	main = "#b79879"
	eye = "#6574c1"
	line = "#3a332d"
	dark = "#b58765"
	lid = "#ddcdbd"
	hand = "#3a332d"
	hair = "#6dadfb"
	tongue = "#953036"
	tail = "#ddcdbd"
	show_all = true